# Generated by Django 4.2.13 on 2024-07-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placename', models.CharField(max_length=200)),
                ('Weather', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='destimages/')),
                ('description', models.TextField()),
            ],
        ),
    ]
