# Generated by Django 4.2.13 on 2024-08-11 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinations',
            old_name='State',
            new_name='Actors',
        ),
        migrations.RenameField(
            model_name='destinations',
            old_name='Weather',
            new_name='Relesedate',
        ),
        migrations.RenameField(
            model_name='destinations',
            old_name='district',
            new_name='Reviews',
        ),
        migrations.RenameField(
            model_name='destinations',
            old_name='Placename',
            new_name='Title',
        ),
    ]
